### ISSUE TITLE
Error occured when using "API reference tool" on Windows 10

### ISSUE THREAD

**Issue by psychelzh** [expyriment/expyriment#142] opened 2018-12-05 02:01 UTC
I am trying to start `API reference tool` on "Windows 10", but in vain. I first start a `python` interpreter, and execute the following two lines:

```python
import expyriment
expyriment.show_documentation(3)
```

Unfortunately, it reports errors like this:

```python
Hello from the pygame community. https://www.pygame.org/contribute.html
Expyriment 0.9.0 (Python 3.7.0)
-m
C:\tools\miniconda3\lib\runpy.py:125: RuntimeWarning: 'expyriment._api_reference_tool' found in sys.modules after import of package 'expyriment', but prior to execution of 'expyriment._api_reference_tool'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "C:\tools\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\tools\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\tools\miniconda3\lib\site-packages\expyriment\_api_reference_tool.py", line 567, in <module>
    show_GUI()
  File "C:\tools\miniconda3\lib\site-packages\expyriment\_api_reference_tool.py", line 103, in show_GUI
    import expyriment.io.extras
  File "C:\tools\miniconda3\lib\site-packages\expyriment\io\extras\__init__.py", line 20, in <module>
    from . import defaults
  File "C:\tools\miniconda3\lib\site-packages\expyriment\io\extras\defaults.py", line 24, in <module>
    exec(_defaults)
  File "<string>", line 1, in <module>
OSError: [Errno 22] Invalid argument: 'C:\tools\\miniconda3\\lib\\site-packages\\expyriment\\io\\extras\\_cedrusresponsedevice_defaults.py'
```

I also tried to start from command line with `cmd` tool:

```cmd
C:\Users\liang>activate base
(base) C:\Users\liang>python -m expyriment.cli -A
```

Again, with the following errors:

```cmd
(base) C:\Users\liang>python -m expyriment.cli -A
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Expyriment 0.9.0 (Python 3.7.0)
-m
Start API Reference Tool

(base) C:\Users\liang>pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Expyriment 0.9.0 (Python 3.7.0)
-m
C:\tools\miniconda3\lib\runpy.py:125: RuntimeWarning: 'expyriment._api_reference_tool' found in sys.modules after import of package 'expyriment', but prior to execution of 'expyriment._api_reference_tool'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Traceback (most recent call last):
  File "C:\tools\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\tools\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\tools\miniconda3\lib\site-packages\expyriment\_api_reference_tool.py", line 567, in <module>
    show_GUI()
  File "C:\tools\miniconda3\lib\site-packages\expyriment\_api_reference_tool.py", line 103, in show_GUI
    import expyriment.io.extras
  File "C:\tools\miniconda3\lib\site-packages\expyriment\io\extras\__init__.py", line 20, in <module>
    from . import defaults
  File "C:\tools\miniconda3\lib\site-packages\expyriment\io\extras\defaults.py", line 24, in <module>
    exec(_defaults)
  File "<string>", line 1, in <module>
OSError: [Errno 22] Invalid argument: 'C:\tools\\miniconda3\\lib\\site-packages\\expyriment\\io\\extras\\_cedrusresponsedevice_defaults.py'
```

**Comment by fladd** [comment] 2018-12-05 09:02
This seems already to be fixed in the current beta. While I could reproduce the error in 0.9.0, I could not reproduce it in [0.9.1b2](https://github.com/expyriment/expyriment/releases/tag/v0.9.1b2). Could you check whether this happens for you with the beta, too?

Concerning the conda error, I have no clue, maybe @lindemann09 can help with that? But seeing that the line the error refers to does not seem to exist anymore in the current code base, I assume that this will also not happen with the beta anymore.

**Comment by psychelzh** [comment] 2018-12-06 01:21
@fladd Thank you very much! As `0.0.1b2` is a pre-release, I'd better wait for next release to test that. For now, I could use the web-based version.

**Closed** 2019-01-09 15:31 UTC
